### ISSUE TITLE
After install in composer and go to start page i hav error

### ISSUE THREAD

**Issue by dpmurm** [reportico-web/yii2-reportico#1]
After install in composer and go to start page i have error.
Projects area does not exist - cannot write project after enter and reenter password.

**Comment by reportico-web** [comment]
Hi there... please give me a couple of days to investigate this
Peter

**Comment by CdaGanache** [comment]
Hi..me too have that error.. please guide me sir~

**Comment by vfarfan** [comment]
i have the same error: "Projects area does not exist - cannot write project". Trying to install on Yii2 Framework, Windows 8, XAMPP & PHP 7.1.1. The installed folder has less files and folders than non-Yii2 version.

**Comment by reportico-web** [comment]
Hi there, Id like to debug this, there seems to be a pathing issue.. 

Does this happen when you try to set the admin password on first install?

can you do me a favour and
edit the file 
vendor/reportico/yii2-reportico/components/reportico.php and around line 5726 there is the function

`function save_admin_password($password1, $password2, $language)
`

can you look a few lines down to line 5759 and you will see

    if ( !@file_exists ( $proj_parent ) )
    {
            $old_error_handler = set_error_handler("\\reportico\\reportico\\components\\ErrorHandler");
            return "Projects area $proj_parent does not exist - cannot write project";
    }

and change this to


    if ( !@file_exists ( $proj_parent ) )
    {
            $old_error_handler = set_error_handler("\\reportico\\reportico\\components\\ErrorHandler");
            return "Admin Folder is $this->admin_projects_folder, Projects area $proj_parent does not exist - cannot write project";
    }
 
Can you then tell me what the debug is when you try again?

If the folder name printed is not a valid path then we need to tweak something in the config.php to perhaps override the admin_projects_folder.

Peter





Peter

**Comment by jairusmartin** [comment]
Peter: with your debug code I received:

`Admin Folder is C:\wamp64\www\blink-reportico\vendor\reportico\yii2-reportico/components/projects, Projects area does not exist - cannot write project`

**Comment by matiullah31** [comment]
I was facing the same issue: but i solve this issue by comment out this line
//$proj_parent = find_best_location_in_include_path( $this->admin_projects_folder);
and use instead this one.
	$proj_parent = $this->admin_projects_folder;

**Comment by reportico-web** [comment]
I think its ok to close this.. let me know if it needs reopening !
