### ISSUE TITLE
Yii2 reportico quick start guide "Creating links to reports" link not found

### ISSUE THREAD

**Issue by thadudexx** [reportico-web/yii2-reportico#10]
Thanks you for the great tool, i love using it.
I found a missing link and some errors in the "see this in action" links.
http://www.reportico.org/yii2/web/index.php/quickstart/embed-links doesnt exist.

**Comment by reportico-web** [comment]
Ok I fixed the link thanks for poiting that out ..should be embedding-links.

I will address the "see this in action" links very soon when i get the version of the module that works with php 7.0. on there.. and i will soon get  out reportico 6.0, a much more composer compliant version , available.. you can try this yourself in yii2 if you do load in the develop version of the module ( might be best trying in a fresh yii install so compare )

so you should get it with this command..

    composer require reportico/yii2-reportico "dev-develop"

Also this version by default uses a different PDF engine phantomjs .. to enable this you need to add to your composer.json scripts section the 3 rd option here for example..
```
    "scripts": {
        "post-install-cmd": [
            "yii\\composer\\Installer::postInstall"
        ],
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject",
            "yii\\composer\\Installer::postInstall"
        ],
        "post-update-cmd": [
            "PhantomInstaller\\Installer::installPhantomJS"
        ]
     },
```

then run 
```
composer update
```

**Comment by reportico-web** [comment]
Closed as time has passed !!
