### ISSUE TITLE
Using Yii2 Advanced and adminlte - no /reportico

### ISSUE THREAD

**Issue by olissongs** [reportico-web/yii2-reportico#11]
ok i tried it in yii advanced too, but nor working
http://backend.yii2_url/index.php/reportico or http://backend.yii2_url/reportico
using the adminlte theme

installed as recommended with composer and add the config in backend/config/main.php

so whats the trick to use it?

**Comment by reportico-web** [comment]
Hi there.. I just installed both yii2 basic and advanced and installed reportico  and it worked for me on Linux PHP7.0 ( it should work on 5.6 )

Can you confirm did you add to the config file to the reportico module  ( for basic is in config/web.php and in advanced you can add it in backend/config/main.php or similar ) 

so in my advanced i have something like ..


```
......
.....
return [
    'id' => 'app-backend',
    'basePath' => dirname(__DIR__),
    'controllerNamespace' => 'backend\controllers',
    'bootstrap' => ['log'],
    'modules' => [
        'reportico' => [
            'class' => 'reportico\reportico\Module' ,
            'controllerMap' => [
                'reportico' => 'reportico\reportico\controllers\ReporticoController',
                'mode' => 'reportico\reportico\controllers\ModeController',
                'ajax' => 'reportico\reportico\controllers\AjaxController',
                ]
            ],
        ]

....
``` 

Also by default Yii2 uses non-clean urls so i had to use

http://path_to_backend/web/index.php?r=reportico

Peter
Let me know if that works.

Also I will send you soon a composer commmand so you can try reportico 6 which works better.

**Comment by olissongs** [comment]
yes that works fine, thank you.

what about the rights in an production evironment, i don'feel very comfortable to bring this write acces into extensions.
how dow you solve this problem?

**Comment by reportico-web** [comment]
Hi there .. glad that works..  which write access are you talking about.. to which folders ?.. the next version may overcome this.

**Comment by reportico-web** [comment]
Hi I will close this, if thats ok?
Please let me know the folders as i think that the next release 6.0.x will solve this problem. You can use
composer require reportico/yii2-reportico dev-develop to get this if you want to try it out but it will require migration
