### ISSUE TITLE
export encoding 

### ISSUE THREAD

**Issue by backersh** [reportico-web/yii2-reportico#3]
Hello 
I have a problem with arabic **(Ù†Ø´Ø§Ø· ÙØ±Ù‚Ø© Ø§Ø¨Ùˆ Ø¹Ù„ÙŠ)** characters when  exporting to pdf or csv  , my db charset is UTF8 and the project encoding for db and output is UTF8 ?! any help to solve this issue  !
@reportico-web

**Comment by reportico-web** [comment]
Closed as this is old, sorry I couldnt provide an answer for this!!
