### ISSUE TITLE
Fatal Error after embeding reportico report on web page

### ISSUE THREAD

**Issue by mateso** [reportico-web/yii2-reportico#4]
I managed to install reportico for my Yii2 web application. When I try to link created report I get this message on a web browser "Fatal Error: Methods with the same name as their class will not be constructors in a future version of PHP; ADODB_pdo has a deprecated constructor"
Below is an image to show what I'm experiencing
![selection_001](https://cloud.githubusercontent.com/assets/5889635/18249546/abd06018-7387-11e6-879d-400e98074281.png)
Thank you for the great tool, your advice will be appriciated

**Comment by reportico-web** [comment]
Thanks very uch for poiting this out

 i think you are using PHP 7 .. I need to upgrade the github version to support this. Hopefully i can do this in the next few days.

**Comment by mateso** [comment]
Yes it's true I'm using PHP version 7.0.8. In mean time I will have to downgrade my PHP. I'm waiting for the upgrade.
Thank you.

**Comment by deadmantfa** [comment]
Hi is this issue resolved? or being worked at?

**Comment by reportico-web** [comment]
Hi there .. it should not take too long to fix this .. thanks for reminding me ... ill try to resolve soon ie within the coming week

**Comment by reportico-web** [comment]
Hi there

Sorry for not updating this thread.
I pushed a new version last November which works with PHP 7 and also has a whole new look. 

This is version 4.6 .. if you composer update this modue you should get this, unless the update isnt working. Can you try this?

Peter

**Comment by deadmantfa** [comment]
Sure will try and get back to you.

**Comment by reportico-web** [comment]
Hope it worked... im closing this now
