### ISSUE TITLE
report not found in perpare execute_mode

### ISSUE THREAD

**Issue by winetou** [reportico-web/yii2-reportico#5]
**my ../reportico/config.php**
``  
// Path relative to public where reportico assets are
    'path_to_assets' => 'packages/reportico/reportico',

    // Path relative to laravel pase or fully where projects will be created
    //'path_to_projects' => __DIR__."/components/projects",
    'path_to_projects' => \Yii::getAlias("@frontend/components/reportico"),

    // Path relative to laravel pase or fully where admin project will be stored
    'path_to_admin' => __DIR__ . "/components/projects",

 **i set this in my report**
$engine->access_mode = "REPORTOUTPUT";                 // Allows access to single specified report
$engine->initial_project_password = "listen";
$engine->initial_execute_mode = "PREPARE";          // Starts user in report criteria selection mode
$engine->initial_project = 'reports';               // Name of report project folder
$engine->initial_report = 'jahresliste';            // Name of report to run
$engine->bootstrap_styles = "3";                    // Set to "3" for bootstrap v3, "2" for V2 or false for no bootstrap
$engine->clear_reportico_session = true;            // Normally required
$engine->bootstrap_preloaded = false;               // auf false setzen da sonst kein modaler Dialog angezeigt wird bei einem Fehler
$engine->emmbedded_report = true;
$engine->execute();

**after execute**
the criteria report
![image](https://cloud.githubusercontent.com/assets/3724090/21765895/c766d928-d66b-11e6-8296-f9adf64e4d02.png)

**then click "submit"**
reportico search the "jahresliste" in the folder "admin" instead of "reports"
![image](https://cloud.githubusercontent.com/assets/3724090/21765874/adc4c6a6-d66b-11e6-88b1-2eed10a9ef6d.png)

**Comment by reportico-web** [comment]
Hi there.... looks like the session isnt being maintained so your project name is being lost.

I'll investigate, can you confirm that the normal reportico designer works fine?

Can you also correct the spelling mistake...
`$engine->emmbedded_report = true;`

should be

`$engine->embedded_report = true;`

Peter

**Comment by winetou** [comment]
Hi Peter,
thank's but it's always the same problem. 

Roland

**Comment by winetou** [comment]
Hi Peter,
i found out the problem. It's the session parameter in the yii2 config.
Default is:
`'session' => [
            'name' => 'FRONTENDSESSID',
            'cookieParams' => [
                'httpOnly' => true,
                'path'     => '/',
            ],` 

when delete the session in my config then work fine. 

Roland
