### ISSUE TITLE
Blank Date in Criteria

### ISSUE THREAD

**Issue by chochoto** [reportico-web/yii2-reportico#7]
Could it set blank value for default of the date in criteria? Also when I blank out one of the dates (textbox) and return to the screen (Back button), then the textbox is hidden (Which is a bug)
![image](https://user-images.githubusercontent.com/30799749/32817137-589cc91e-ca10-11e7-9b68-61d61b6efc76.png)

**Comment by reportico-web** [comment]
I have modified reportico in the past for this .. ill see if i can work out how to do it in next couple of days

**Comment by chochoto** [comment]
Thank you for your help.

**Comment by reportico-web** [comment]
Sounds like it worked .. closing this
