### ISSUE TITLE
Will not work with yii2-advanced-template?

### ISSUE THREAD

**Issue by tholag** [reportico-web/yii2-reportico#8]
As mentioned above, I cannot use this extension with the yii2-advanced-template.

After installing via composer I tried copying the mentioned config-section into:
```
.../common/config/main.php under "modules", like it is mentioned in the instructions.
.../common/config/main.php under "components", like it is mentioned somewhere else.
```

As well as:
```
.../frontend/config/main.php (both ways)
.../backend/config/main.php (both ways)
```

I guess tried every thinkable url that could have made sense for every of the above files, but I can't get a route to the reportico-controller to work: Page not found (404). Any hints?

Btw: I'm using pretty urls.

Any help appreciated, thanks!

UPDATE:
Solved... it DOES work with yii2-advanced-template as expected.

**Comment by reportico-web** [comment]
Great news tholag!! hope it works well for you!

**Comment by olissongs** [comment]
ok i tried it in yii advanced too, but nor working
http://backend.yii2_url/index.php/reportico or http://backend.yii2_url/reportico
using the adminlte theme

installed as recommended with composer and add the config in backend/config/main.php

so whats the trick to use it?
